/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Hello: typeof import('./src/components/hello/hello.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Hex: typeof import('./src/components/hello/components/hex.vue')['default']
    Hex1: typeof import('./src/components/hello/components/hex1.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
