/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AnswerAnalyMask: typeof import('./src/components/answerAnalyMask/answerAnalyMask.vue')['default']
    DoTopics: typeof import('./src/components/doTopics/doTopics.vue')['default']
    GridBorder: typeof import('./src/components/gridBorder/gridBorder.vue')['default']
    Hello: typeof import('./src/components/hello/hello.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Hex: typeof import('./src/components/hello/components/hex.vue')['default']
    Hex1: typeof import('./src/components/hello/components/hex1.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SkillExplainMask: typeof import('./src/components/skillExplainMask/skillExplainMask.vue')['default']
  }
}
