/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/classifyArea/': RouteRecordInfo<'/classifyArea/', '/classifyArea', Record<never, never>, Record<never, never>>,
    '/classifyKind/': RouteRecordInfo<'/classifyKind/', '/classifyKind', Record<never, never>, Record<never, never>>,
    '/classifyNecessary/': RouteRecordInfo<'/classifyNecessary/', '/classifyNecessary', Record<never, never>, Record<never, never>>,
    '/exercise/': RouteRecordInfo<'/exercise/', '/exercise', Record<never, never>, Record<never, never>>,
    '/home/': RouteRecordInfo<'/home/', '/home', Record<never, never>, Record<never, never>>,
    '/login/': RouteRecordInfo<'/login/', '/login', Record<never, never>, Record<never, never>>,
  }
}
